name: Build Poetry

on:
  workflow_call:
    inputs:
      application-name:
        description: 'Name of the application/package'
        required: false
        type: string
      poetry-image:
        description: 'Container image to use for building'
        required: false
        type: string
        default: 'ghcr.io/srekit/custom-images/build-poetry:pr-3-a1d2d7d'
      poetry-version:
        description: 'Poetry version to use'
        required: false
        type: string
        default: '1.8.0'
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.13'

jobs:
  quality-and-security-checks:
    name: Quality and Security Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      pull-requests: write
    container:
      image: ${{ inputs.poetry-image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Poetry Quality Checks
        uses: srekit/github-workflows/.github/actions/poetry-quality-checks@feature/build-poetry-workflow
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          poetry-version: ${{ inputs.poetry-version }}
          python-version: ${{ inputs.python-version }}

      - name: Run Poetry Security Scan
        uses: srekit/github-workflows/.github/actions/poetry-security-scan@feature/build-poetry-workflow
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          poetry-version: ${{ inputs.poetry-version }}
          python-version: ${{ inputs.python-version }}

  generate-artifacts:
    name: Generate Artifacts
    needs: [quality-and-security-checks]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container:
      image: ${{ inputs.poetry-image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4

      - name: Generate Poetry Artifacts
        id: generate-poetry-artifacts
        uses: srekit/github-workflows/.github/actions/poetry-artifacts@feature/build-poetry-workflow
        with:
          python-version: ${{ inputs.python-version }}

  generate-container-image:
    name: Generate Container Image
    needs: [generate-artifacts, quality-and-security-checks]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Image Name
        id: generate-image-name
        uses: srekit/github-workflows/.github/actions/generage-image-name@feature/build-poetry-workflow

      - name: Generate image tag
        id: generate-tag
        uses: srekit/github-workflows/.github/actions/generate-tag@feature/build-poetry-workflow
        with:
          target-branch: ${{ inputs.target-branch }}

      - name: Build and Push Container
        uses: srekit/github-workflows/.github/actions/container-build@feature/build-poetry-workflow
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ steps.generate-image-name.outputs.image-name }}
          tags: ${{ steps.generate-tag.outputs.tag }}
