name: Build Poetry

on:
  workflow_call:
    inputs:
      application-name:
        description: 'Name of the application/package'
        required: true
        type: string
      poetry-image:
        description: 'Container image to use for building'
        required: false
        type: string
        default: 'ghcr.io/srekit/custom-images/build-poetry:pr-3-a1d2d7d'

jobs:
  quality-and-security-checks:
    name: Quality and Security Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      pull-requests: write
    container:
      image: ${{ inputs.poetry-image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Poetry Quality Checks
        uses: srekit/github-workflows/.github/actions/poetry-quality-checks@feature/build-poetry-workflow
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          poetry-version: '1.8.0'
          python-version: '3.13'

      - name: Run Poetry Security Scan
        uses: srekit/github-workflows/.github/actions/poetry-security-scan@feature/build-poetry-workflow
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          poetry-version: '1.8.0'
          python-version: '3.13'

  build:
    name: Build Package
    needs: [quality-and-security-checks]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Image Name
        id: image-name
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ inputs.application-name }}"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Generate image tag
        id: generate-tag
        uses: srekit/github-workflows/.github/actions/generate-tag@main
        with:
          target-branch: ${{ inputs.target-branch }}

      - name: Build and Push Container
        uses: srekit/github-workflows/.github/actions/container-build@feature/build-poetry-workflow
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ steps.image-name.outputs.IMAGE_NAME }}
          tags: |
            ${{ steps.generate-tag.outputs.tag }}

      #- name: Upload Artifacts
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: dist
      #    path: dist/
